version: "3"
services:
  postgis:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "5438:5432"
    volumes:
      - db-data:/data
      - ./:/usr/src/app
    env_file:
      - ./config.env

volumes:
  db-data:
