FROM geographica/postgis:breezy_badger

MAINTAINER Cayetano Benavent "cayetano.benavent@geographica.gs"


# Environment
ENV PGROUTING_VERSION develop
ENV CGAL_VERSION 4.9
ENV OSM2PGR_VERSION develop

# Sources
ADD https://github.com/pgRouting/pgrouting/archive/${PGROUTING_VERSION}.tar.gz $ROOTDIR/src/pgrouting/
ADD https://github.com/CGAL/cgal/archive/releases/CGAL-${CGAL_VERSION}.tar.gz $ROOTDIR/src/cgal/
ADD https://github.com/pgRouting/osm2pgrouting/archive/${OSM2PGR_VERSION}.tar.gz $ROOTDIR/src/osm2pgrouting/
ADD compile.sh $ROOTDIR/src/

# Compilation
RUN chmod 777 src/compile.sh
RUN src/compile.sh

# Install Python3 dependencies
RUN apt-get update -y && apt-get install -y python3-pip
RUN python3 -m pip install requests
RUN python3 -m pip install psycopg2

WORKDIR /usr/src/app/
